### ISSUE TITLE
Issue #6

### ISSUE THREAD

**Issue by DennyTim** [AllenPeter25/task#6]
https://github.com/AllenPeter25/task/blob/2426676bcf31a455633dbcbbb9d02260a4fe4603/styles.css#L8

Contextually right way with width, but better to bring a special container for each section of the page.
If you wanna use width restrictions for the page, you need to use the following structure:
```html
<header class="...">
   <div class="container">...</div>
</header>
<main class="...">
   <div class="container">...</div>
</main >
<footer class="...">
   <div class="container">...</div>
</footer>
```
```css
.container {
    width: 960px;
    margin: 0 auto;
    text-align: center; /* can be used optionally if you wanna align the whole section */
}
```
